function [Pathloss] = Longley_Rice(centralFrequency_MHz,...
    transmitter_lan, transmitter_lon,...
    receiver_lan, receiver_lon,...
    antennaPolarization, groundConductivity,...
    groundPermittivity, atmosphericRefractivity,...
    climateZone, timeVariablityTolerance,...
    situationVariabilityTolerance)
tx = txsite('Latitude',transmitter_lan,'Longitude',transmitter_lon,...
    'TransmitterFrequency',centralFrequency_MHz);
rx = rxsite('Latitude',receiver_lan,'Longitude',receiver_lon);
pm = propagationModel('longley-rice',...
    'AntennaPolarization',antennaPolarization,...
    'GroundConductivity',groundConductivity,...
    'GroundPermittivity',groundPermittivity,...
    'AtmosphericRefractivity',atmosphericRefractivity,...
    'ClimateZone',climateZone,...
    'TimeVariabilityTolerance',timeVariablityTolerance,...
    'SituationVariabilityTolerance',situationVariabilityTolerance);
Pathloss = pathloss(pm,rx,tx);
end